/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_libose_WRAP_H_
#define SWIG_libose_WRAP_H_

class SwigDirector_OSEBase : public OSEBase, public Swig::Director {

public:
    SwigDirector_OSEBase();
    virtual ~SwigDirector_OSEBase();
    virtual void init();
    virtual void *getfnptr(char const *const fname);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(char *);
    void swig_connect_director(SWIG_Callback0_t callbackinit, SWIG_Callback1_t callbackgetfnptr);

private:
    SWIG_Callback0_t swig_callbackinit;
    SWIG_Callback1_t swig_callbackgetfnptr;
    void swig_init_callbacks();
};

class SwigDirector_OSECsharpBase : public OSECsharpBase, public Swig::Director {

public:
    SwigDirector_OSECsharpBase();
    virtual ~SwigDirector_OSECsharpBase();
    virtual void init();
    virtual void *getfnptr(char const *const fname);
    virtual void ose_println(ose_bundle osevm);
    virtual void ose_sendto(ose_bundle osevm);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(char *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackinit, SWIG_Callback1_t callbackgetfnptr, SWIG_Callback2_t callbackose_println, SWIG_Callback3_t callbackose_sendto);

private:
    SWIG_Callback0_t swig_callbackinit;
    SWIG_Callback1_t swig_callbackgetfnptr;
    SWIG_Callback2_t swig_callbackose_println;
    SWIG_Callback3_t swig_callbackose_sendto;
    void swig_init_callbacks();
};


#endif
