//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ose_errno {
  OSE_ERR_NONE = 0,
  OSE_ERR_TYPE,
  OSE_ERR_ELEM_TYPE,
  OSE_ERR_ITEM_TYPE,
  OSE_ERR_ELEM_COUNT,
  OSE_ERR_ITEM_COUNT,
  OSE_ERR_RANGE,
  OSE_ERR_UNKNOWN_TYPETAG,
  OSE_ERR_UNKNOWN_CONTEXT_BUNDLE
}
