//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ose_match_retval {
  OSE_MATCH_NOMATCH = 0,
  OSE_MATCH_ADDRESS_COMPLETE,
  OSE_MATCH_PATTERN_COMPLETE,
  OSE_MATCH_BOTH_COMPLETE,
  OSE_MATCH_ERROR_UNMATCHED_LEFT_SQUARE_BRACKET,
  OSE_MATCH_ERROR_UNMATCHED_RIGHT_SQUARE_BRACKET,
  OSE_MATCH_ERROR_UNMATCHED_LEFT_CURLY_BRACE,
  OSE_MATCH_ERROR_UNMATCHED_RIGHT_CURLY_BRACE,
  OSE_MATCH_ERROR_PATTERN_NO_LEADING_SLASH,
  OSE_MATCH_ERROR_ADDRESS_NO_LEADING_SLASH,
  OSE_MATCH_ERROR_INVALID_CHARACTER_CLASS,
  OSE_MATCH_ERROR_BACKTRACK_LIMIT_EXCEEDED,
  OSE_MATCH_ERROR_INVALID_REPETITION
}
