#include <stdio.h> // for snprintf

#include "osesdk_types.h"
#include "libose/ose_context.h"
#include "libose/ose_util.h"
#include "libose/ose_stackops.h"
#include "libose/ose_vm.h"

#define OSEVM_EVALTYPE_ADDR_PREFIX "/type/"
#define OSEVM_EVALTYPE_ADDR_SUFFIX "/evalType"
const char * const OSEVM_EVALTYPE_ADDR_TYPESTR[128] =
{
    "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "",

    OSEVM_EVALTYPE_ADDR_PREFIX " " OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "!" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "\"" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "#" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "$" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "%" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "&" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "'" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "(" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX ")" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "*" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "+" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "," OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "-" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "." OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "/" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "0" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "1" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "2" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "3" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "4" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "5" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "6" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "7" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "8" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "9" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX ":" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX ";" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "<" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "=" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX ">" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "?" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "@" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "A" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "B" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "C" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "D" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "E" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "F" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "G" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "H" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "I" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "J" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "K" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "L" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "M" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "N" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "O" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "P" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "Q" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "R" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "S" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "T" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "U" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "V" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "W" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "X" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "Y" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "Z" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "[" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "\\" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "]" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "^" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "_" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "`" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "a" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "b" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "c" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "d" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "e" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "f" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "g" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "h" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "i" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "j" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "k" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "l" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "m" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "n" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "o" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "p" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "q" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "r" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "s" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "t" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "u" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "v" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "w" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "x" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "y" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "z" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "{" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "|" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "}" OSEVM_EVALTYPE_ADDR_SUFFIX,
    OSEVM_EVALTYPE_ADDR_PREFIX "~" OSEVM_EVALTYPE_ADDR_SUFFIX,
    ""
};

void osesdk_evalType(ose_bundle osevm)
{
    ose_bundle vm_s = OSEVM_STACK(osevm);
    int32_t o, s, n;
    enum ose_errno e = ose_getLastBundleElem(vm_s, &n, &o, &s);
    if(e != OSE_ERR_NONE)
    {
        return;
    }
    if(ose_getBundleElemType(vm_s, o) == OSETT_BUNDLE)
    {
        const char * const buf =
            OSEVM_EVALTYPE_ADDR_TYPESTR[(unsigned)OSETT_BUNDLE];
        int32_t lasto = ose_readSize(vm_s);
        ose_pushString(vm_s, buf);
        OSEVM_LOOKUP(osevm);
        if(ose_getBundleElemType(vm_s, lasto) == OSETT_MESSAGE
           && ose_peekMessageArgTypeAtOffset(vm_s, lasto) == OSETT_BLOB)
        {
            osevm_apply(osevm);
        }
        else
        {
            ose_dropAtOffset(vm_s, lasto);
        }
    }
    else
    {
        int32_t lasto = ose_readSize(vm_s);
        char tt;
        tt = ose_peekMessageArgTypeAtOffset(vm_s, o);
        const char * const buf =
            OSEVM_EVALTYPE_ADDR_TYPESTR[(unsigned)tt];
        ose_pushString(vm_s, buf);
        OSEVM_LOOKUP(osevm);
        if(ose_peekMessageArgTypeAtOffset(vm_s, lasto) == OSETT_BLOB)
        {
            osevm_apply(osevm);
        }
        else
        {
            ose_dropAtOffset(vm_s, lasto);
        }
    }
}
